### ISSUE TITLE
Complete Linux desktop app installation instructions

### ISSUE THREAD

**Issue by john-light** [cryptocat/cryptocat#100]
The crypto.cat home page just provides a `.zip` file. What is the user supposed to do with this file? Complete installation instructions should be provided.

**Comment by kaepora** [comment]
Agreed. I'll accept help on this as I'd rather focus on other things, but I do see how it's important.

**Comment by kaepora** [comment]
Is there some kind of installer creation tool for Linux?

**Comment by ledti** [comment]
It's mostly left to downstream (the distributions) to create packages, but if upstream (kaepora) wish to, they'll generally provide .deb and .rpm packages, along with a signed source zip and/or tar.gz file(s) with instructions on how to compile the program.

Generally, if downstream distributions intend to include a program in their repositories, they _greatly_ prefer source files with which to compile themselves, so as to avoid statically linked blobs.

As far as I know, there's no easy tool that will compile both .deb/.rpm files for you. Since this is a one man project, I wouldn't worry about providing distribution specific packages.

As for installer creation tools, there is [MojoSetup](http://icculus.org/mojosetup/) which is basically a smart installer/extractor. If you have any gog.com games, this is what their Linux installers use.

A different approach is [AppImage](http://appimage.org/), which is basically the equivalent of a single-binary portable .exe file. It doesn't create any .desktop/menu entries, and the user has to run the .appimage file every time they want to run the application.

**Comment by kaepora** [comment]
Maybe I can provide `deb` and `rpm` packages.

**Comment by tuxication** [comment]
I did a package for Archlinux. I would gladly support it and add it to the repository if wanted. (I wanted to wait after the beta to avoid the need to update it everyday).

**Comment by probonopd** [comment]
I can do an [AppImage](http://appimage.org) if there is interest.

**Comment by kaepora** [comment]
Please don't. I am responsible for packaging, signing and distribution. I'll handle this soon.

**Comment by bugissue** [comment]
was this fixed? because when i download cryptocat and extract it to a folder i literally just double clicked Cryptocat and it not only runs fine it is also now available when i search for applications and allows me to save it to my dock (using ubuntu gnome 16.04)

i've never downloaded a linux application like this and had it run so smoothly usually i add a repository and use apt-get install

**Comment by kaepora** [comment]
@bugissue This is the current intended functionality, but as part of this issue we intend to make things still more convenient for Linux users.

**Comment by nanicpc** [comment]
Actually I like the fact that is just "download and have fun!" (Ubuntu user)

**Comment by cats-meow** [comment]
Instructions for installing CryptoCat in Linux MINT 17.3 MATE version

1
Download for example Cryptocat_v3.1.26_160622-linux-x64.zip

2
Double-click the ZIP file

3
Inside the ZIP file double-click Cryptocat.zip

4
Continue by double-clicking Cryptocat-linux-x64
You should now see 12 files, which you will later copy so leave this window open and arrange its position and size to always be visible.

5
Use the file manager to create a hidden folder under your home directory
normally this is /home/your-name

6
Attention, in a Linux system, NEVER use a name with spaces as a folder name.
Should you need spaces, use hyphen or underline characters.

7
Before doing this, if necessary the short-cut CTRL-h will allow seeing all hidden directories.
CTRL-h is a toggle switch.  Now you see, now you do not.

8
Use the name .cryptocat as the name of the hidden directory.  Notice the dot with no space at the beginning.
Create this directory under your-name directory (folder).

9
In the window opened in step 4, click-left on one of the 12 files, then the key combination CTRL-A to mark all files.
Either click-right and copy or use key combination CTRL-C in order to copy all files to temporary storage.

10
Now copy all files into the /home/your-name/.cryptocat folder that you created in step 8 by right-clicking and pasting into /home/your-name/.cryptocat

11
I have a bar at the top of the screen that I created by clicking in an empty space on the bottom bar, then left-click on new panel.

12
A right-click on this top panel then click add to panel.  Left-click on Custom Application Launcher/Create a new launcher.
Then click on ADD.  For the app name use cyryptocat.  To find the command click on browse.
Then navigate to /home/your-name until you see home/your-name/.cryptocat and double-click that folder.
If necessary, repeat pressing CTRL-h to be able to see hidden folders.
Arrange size and position of this window so it is always visible.
Choose the application by selecting the file Cryptocat that has about 66 Mbyte size.  Then click on OPEN.
Do NOT click on OK.

13
In the top-left part of this window there is a stupid-looking icon button.  Click-left on this button and navigate to /home/your-name/.cryptocat
until you see the file logo.png.  Select this file, then click OPEN.  Then click OK to exit the launcher creation and you will have a cryptocat icon in you top bar.
Icons in the top bar only need to be clicked once to launch the app.

14
Toggle CTRL-h in your file explorer so all the hidden files disappear to make things less confusing.

**Comment by kaepora** [comment]
@cats-meow Thanks for taking the time to write that draft.

**Comment by cats-meow** [comment]
I am not a programmer, so I return to the community that what I can do.
Thank you for CryptoCat.

**Comment by ITwrx** [comment]
first, i would request an improvement to the below quoted text. It sounds as if "Linux the OS" is missing something. GPG **is** the "built-in standard for code signatures", for instance. Just because there may not be a way exposed graphically via a particular file manager doesn't mean there's not a "built in standard".   Furthermore, on a Gnu+Linux distribution, that is a function package managers can (and should, IMHO) handle anyways, as alluded to in the quote. Though, i understand why app devs would want to distribute their packages directly, especially for slower moving distros. 

> Since Linux comes with no built-in standard for code signatures (aside from package managers, which are distribution-specific), each Cryptocat for Linux release comes with a PGP signature that can be verified using gpg.

I would recommend just providing instructions for installation on whichever GNU+Linux distributions you wish to support and source+binary instructions **or** source+binary(which cryptocat already does) and a note to "check with your distribution for packages and package management instructions". 

If cryptocat wants to include the instructions generously provided by @cats-meow then that is useful for people who wish to "install" that way, but the it shouldn't be misrepresented as "installing" as that's just placing the binary somewhere and creating a shortcut for running it directly. "Installing" means a package manager installs it, knows about it, can update it when an update is available, and can remove it on command.  I have no opinion as to whether cryptocat should try to to package for different distro's package managers or not, but getting and installing packages from distribution repos via package managers is superior to downloading random binaries from all over the internet in my opinion, not some deficiency with Linux(not that Cryptocat was saying it was. It could just possibly be interpreted that way) . Maybe just note the two overall installation options(download our binary or use your distro's package manager) and provide relevant instructions.

I use Arch for instance. someone has generously already uploaded it to the AUR. This (unofficial, user supplied) package doesn't handle the gpg key import and verification so you just have to try to install it (i used the aur package helper application, packer-color). It will fail with 

> gpg: Signature made Tue 30 Aug 2016 05:47:56 AM CDT
gpg:                using RSA key AB266CB76091B1F8
gpg: Can't check signature: No public key
==> ERROR: A failure occurred in prepare().
    Aborting...
The build failed.

so, import the key it complained about with: 

> gpg --keyserver pgp.mit.edu --recv-keys AB266CB76091B1F8

or whatever keyserver you want to use. Then, while building the package, packer-color reports:

> gpg: Good signature from "Nadim Kobeissi <nadim@nadim.computer>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: FA21 CD53 6312 FADF 9B5D  D804 AB26 6CB7 6091 B1F8

so, it would be useful if Cryptocat could publish the signer info as well as the key fingerprint with each release so that those can be verified when installing manually or by the package manager software when it's installing.

Thanks for Cryptocat and for supporting Gnu+Linux as a platform.

**Comment by greyspectrum** [comment]
This is kind of a hack, admittedly, but I wrote a shell script that functions as an installer for Cryptocat on Linux:

https://github.com/greyspectrum/install-cryptocat

The script fetches Cryptocat from the project website, verifies the GPG signature, installs Cryptocat, and creates a start-up script in `~/bin` so that the user can launch Cryptocat by typing `cryptocat` in the terminal. If the GPG signature fails, then the script will: warn the user, abort the install, and wipe the files it downloaded. 

Offering `deb` and `rpm` packages is probably a better long term solution, but this script may make things easier for some users who don't want to go through the process of manually unpacking and verifying an installation or update.

**Comment by gabrix73** [comment]
32bit ?

**Comment by kaepora** [comment]
Cryptocat will be distributed as an AppImage as of update `3.2.08`.

**Comment by heyakyra** [comment]
Why is it still distributed in a zip? #240
