### ISSUE TITLE
Debian install fail without nodejs-legacy

### ISSUE THREAD

**Issue by kcdtv** [cryptocat/cryptocat#13]
Hi there!
  First i would like to congrats the author and wish a long live to the project :smile: 
For the debian (and derivate OS)  users, you will have probably notice that you need to install **npm** before starting the installation process
<code>sudo apt-get install npm</code>
Than, before installing the dependencies, you need to install **nodejs-legacy** otherwise you will get this kind of error when installing **electron-prebuilt**: 
<code>sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
</code>
With **debian**, **ubuntu**, **linux mint** etc it is easy, just do a simple
<code>sudo apt-get install nodejs-legacy</code>
Job is done and you are ready to install cryptocat in your favorite GNU-linux distribution...

I am not used (at all) to javascript and have some difficulties to execute **cryptocat** even-though it seems to be properly installed 
<code>  sudo grunt linux
Running "string-replace:dist" (string-replace) task
File src/package.json created.
File src/js/version.js created.

Running "electron:linux" (electron) task
Downloading electron-v0.37.2-linux-x64.zip
[============================================>] 100.0% of 39.86 MB (843.51 kB/s)
Packaging app for platform linux x64 using electron v0.37.2

Running "exec:linuxLogo" (exec) task

Running "exec:linuxClean" (exec) task

Running "exec:linuxZip" (exec) task

Running "exec:linuxRmDir" (exec) task

Running "exec:writeVer" (exec) task

Done, without errors.
</code>

  May i suggest to the author to complete the readme in order to help useless people like me that cannot execute the tool.
  thanks again for your patience, byeeee

**Comment by kaepora** [comment]
The README assumes familiarity with deploying `node` and will not be elaborated beyond what is necessary.

**Comment by kcdtv** [comment]
> The README assumes familiarity with deploying node and will not be
> elaborated beyond what is necessary.

Huh...
  ...Unless i missed something, the README (it is not that long) does not
assume... anything :
  There is not a single world about being familiarized with javascript,
node or something like this.
  What I can read on your website this  :

> Cyptocat is free software with a simple mission: *everyone should be able
> to chat with their friends in privacy.*

  I am a bit confused : Unfortunately in "real life" not everybody has the
time to learn javascript and get familiarized with node too launch an
application.
    Making a correct documentation with complete installation and use
instructions is a key point if you want to "democratize" access to privacy,
believe me. :D
  It is a simple task if you would use collaboration...
... But, yeah... nvmd...Thanks anyway for your effort and good luck with
your project. Au revoir.

2016-03-30 12:27 GMT+02:00 Nadim Kobeissi <notifications@github.com>:

**Comment by kfogel** [comment]
It might be good for the README to state explicitly that familiarity with node deployment is assumed -- i.e., the issue is not so much the assumption itself as the fact that the assumption is (currently) unstated.  I think this would address @kcdtv's point.

Best regards,
-Karl

**Comment by kcdtv** [comment]
Hi karl.

> I think this would address @kcdtv's point.

Partially and not in a "very satisfactory" way :cat:
My real point is that sir kaepora proudly announces that


> Cryptocat is free software with a simple mission: everyone should be able to chat with their friends in privacy. 


  But in the same time he has such an attitude and so little concern about average users... 
...The mission of this tool is a failure  
  
  Anyway, don't worry karl, we, people without university doctorate degree, won't ever use cryptocat and that's it,
 There are many solution around which are designed for open source systems with kind and talented  developers. 
  It is, by the way, very doubtful to "promote" safety and security and pretend to reach anonymity with a tool apparently mainly oriented to a "backdoored" corporative operative system. (aka winodoz for which there is an .exe "for noobs")
  Some might say it is absurd and i hope that a political dissident that really needs anonymity in a dictatorship won't ever think about using cryptocat for windozzz, for his own safety. 
   My cat and myself say good by to you karl and hope for the author that he will manage one day to escape from his university bubble and land on earth...
Meow :smirk_cat:

**Comment by kfogel** [comment]
Hi, @kcdtv.  I disagree, because building software from source at all is _already_ way beyond the knowledge or experience of most users (and that's okay).  A system's documentation always has to start by characterizing its intended audience.  One can't write documentation for a "general audience", nor can one write documentation to satisfy the union of all possible audiences, for such documentation would be unmanageably long and effectively impossible for any given audience to read.

So if @kaepora wants to say that the audience for source-tree build documentation is "developers who are comfortable with Node", that's fine.  It's just that it's helpful to actually _say_ so, so that people can quickly recognize whether they are a member of the intended audience or not.

(Here's a thought experiment: if @kaepora had covered all the Node basics, in the README.md, so that Node knowledge were not a prerequisite, would you have complained about how the documentation assumes a user who's comfortable running commands at a command-line prompt?  Probably not, because *that* particular set of users would have fallen within your assumption zone -- so you wouldn't have noticed the audience assumption then.  @kaepora just has a differently-shaped assumption zone from you.  Neither is invalid or valid, objectively speaking.  Just document the zone, so people can easily tell whether they are inside it or outside it.)

**Comment by kaepora** [comment]
@kfogel Don't ever change.

@kcdtv A reminder that I liberally ban people who abuse the GitHub issue tracker. I run this project purely out of my own time and don't owe anyone anything.
