### ISSUE TITLE
Digitally signed distribution files

### ISSUE THREAD

**Issue by ph4r05** [cryptocat/cryptocat#214]
It would help a lot in increasing a security level and trust if the distribution files downloadable from the web page (zip) would be digitally signed with an author key. Also the page should encourage users to verify the signature after download.

Moreover it would be quite nice to do [reproducible builds].

[reproducible builds]: https://reproducible-builds.org/

**Comment by kaepora** [comment]
All Cryptocat downloads are already digitally signed and [instructions for verifying signatures](https://crypto.cat/help.html#signatures) have existed since the launch of version 3.0.

Please note that I usually ban people from the issue tracker when they open issues clearly without reading the documentation or searching for past issues.

**Comment by ph4r05** [comment]
wow, great! thanks.
Maybe you can take this as UX feedback. Do you think people read all the docs first before using the app? Link on the signature verification on the web would be maybe nice.

And what about reproducible builds? I haven't found anything about this in previous issues.

Feel free to ban if that makes you happy.
