### ISSUE TITLE
Re-implement Cat Sticker Animations

### ISSUE THREAD

**Issue by defuse** [cryptocat/cryptocat#27]
Nadim's tweets led me to believe the cat emoticons are animated, rocking back and forth. However, they don't do this for me. I can't upload a video to github but you can be convinced they aren't moving by noting that the cats are all lined up in the following screenshot:

![catbug](https://cloud.githubusercontent.com/assets/4211072/14163380/fef9e6fe-f6b1-11e5-8d7a-4a709c91597d.png)

What information can I provide to assist in debugging this?

**Comment by kaepora** [comment]
Unfortunately, these animations were temporarily disabled in [update 3.0.17](https://crypto.cat/news.html#releaseAnnouncement) due to CSS3 animations using too much CPU power. The animations will soon be returned as GIFs or some other less power-hungry format.

I'll leave this ticket open anyway since we need a ticket for this.

By the way, it's good to hear from you, Taylor.
