### ISSUE TITLE
User Avatars

### ISSUE THREAD

**Issue by kaepora** [cryptocat/cryptocat#36]
Users should be able to set a small avatar photo. Why not? Makes the client more personable.

Relevant spec: [XEP-0084](http://xmpp.org/extensions/xep-0084.html).

I think I'm leaning towards storing avatars on servers as `image/png` DataURIs with a cap of 40KB per avatar and mandatory dimensions of 128x128.

If this is implemented the [documentation](https://crypto.cat/help.html) should make sure to note how avatars are not encrypted (being general metadata.)

**Comment by TumM0reNcE5SsIti** [comment]
Would it auto-magically remove EXIF data, and make the image completely read-only so that users would have to screenshot the client in order to "steal" the image? Ensuring secrecy of the users avatar would be inherently safer than allowing additional data to make it to the server, potentially identifying a user.

**Comment by kaepora** [comment]
@TumM0reNcE5SsIti That's beyond Cryptocat's threat model responsibilities/coverage.
