### ISSUE TITLE
On OS X don't use pkg

### ISSUE THREAD

**Issue by taoeffect** [cryptocat/cryptocat#45]
The PKG asks for the user's root password. Cryptocat doesn't need root to operate. It's convention for OS X software to be distributed either as a zipped app bundle that's dragged into `/Applications`, or as a DMG that has an alias for dragging & dropping into `/Applications`.

**Comment by taoeffect** [comment]
I.e. it's good habit to be honest with users, and this message is untruthful:
![screen shot 2016-04-05 at 11 52 43 am](https://cloud.githubusercontent.com/assets/138706/14294254/f6792734-fb24-11e5-83ff-8d4b6bb814b1.jpg)

**Comment by kaepora** [comment]
> I.e. it's good habit to be honest with users, and this message is untruthful:

Dealing with issue tickets from you is literally a headache. I'm not using an expression here: you give me actual headaches. This is the third issue today (out of your grand total of three) that's been completely inane.

> It's convention for OS X software to be distributed either as a zipped app bundle that's dragged into /Applications, or as a DMG that has an alias for dragging & dropping into /Applications.

You are again [completely wrong](https://developer.apple.com/library/mac/documentation/IDEs/Conceptual/AppDistributionGuide/DistributingApplicationsOutside/DistributingApplicationsOutside.html). On top of the fact that this isn't what Apple recommends, having users use a .zip or, worse, a drag-and-drop DMG makes it so that we can't exploit `pkg` strengths, which is having a click-to-install wizard that can also install updates on top of older versions.

The installer isn't being "untruthful with users." and I'm not instructing it to deceive my Mac user base. It was configured to ask for administrative privileges because, by default, Mac users will expect to find the application in `/Applications` and this seemed like the most sensible way to make the installer proceed without issue and a high success rate.

I've looked into having Distribution-format packages and I'm happy to say that the next Cryptocat update *will* allow you to either install for yourself (no admin password) or for the entire machine (admin password.)

You've wasted my entire morning.
